### ISSUE TITLE
SMS 2-way gateway.

### ISSUE THREAD

**Issue by scuba323** [cjones/madcow#19]
I saw in the wiki that is isn't documented. How does one achieve this gateway?

**Comment by cjones** [comment]
My bad, this got removed some time ago. Anyway, the name is sort of misleading. what it really was was an *email* gateway. The idea was to send emails (with picture attachments) from your mobile to a mailbox you set up on the machine, then use procmail or similar to pipe those messages to a script that parsed the MIME envelope, extracted the attached images, and put them in some directory, where presumably you'd serve them via HTTP. This was useful some 10 years ago but nobody does it that way so I retired it. I recommend just putting them in some cloud service and posting a link..
